---
title: "NYC Restaurant Inspection Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(flexdashboard)
```

```{r}
data(rest_inspec)

rest_inspec = rest_inspec %>% 
  mutate(month = lubridate::floor_date(grade_date, unit = "month")) %>% 
  select(
    borough = boro, cuisine = cuisine_description, score, critical_flag, street, month, grade_date, inspection_type) %>% 
  filter(
    borough == "MANHATTAN",
    inspection_type == "Cycle Inspection / Initial Inspection",
    critical_flag == "Not Critical",
    score %in% 0:30,
    cuisine %in% c("Bakery", "Asian", "French", "Italian", "Chinese", "Japanese", "Korean", "Thai", "English", "Turkish", "Russian")
  ) %>% 
  drop_na(grade_date)
```

Column {data-width=600}
-----------------------------------------------------------------------

### Line Plot for Number of Restaurants Graded in Each Month

```{r}
rest_inspec %>% 
  count(month) %>% 
  mutate(
  text_label = str_c("Graded Restaurant Number: ", n)
  ) %>% 
  plot_ly(
    x = ~month, y = ~n,
    type = "scatter", mode = "lines+markers",
    alpha = .6, text = ~text_label
  ) %>% 
  layout(
         xaxis = list(title = 'Month'), 
         yaxis = list(title = 'Number of Restaurants Graded')
         )
```

Column {data-width=400}
-----------------------------------------------------------------------

### Box Plot of Scores for Each Cuisine Category

```{r}
rest_inspec %>% 
  mutate(cuisine = fct_reorder(cuisine, score)) %>% 
  plot_ly(
    y = ~score, color = ~cuisine,
    type = "box", colors = "viridis"
  )
```

### Bar Plot of Number of Restaurants for Each Cuisine Category

```{r}
rest_inspec %>% 
  count(cuisine) %>% 
  mutate(cuisine = fct_reorder(cuisine, n)) %>% 
  plot_ly(
    x = ~cuisine, y = ~n, color = ~cuisine, 
    type = "bar", colors = "viridis"
  ) %>% 
  layout(yaxis = list(title = 'Number of Restaurants'))
```

